// Per-entity column definitions — the single source of truth for the template adapter
// (header → field + type coercion), the validator (required + controlled lists), and the
// downloadable blank templates. Headers are the Prisma field names (near pass-through).
import type { FieldDef, ImportEntity } from "./types";

export const TEMPLATE_COLUMNS: Record<ImportEntity, FieldDef[]> = {
  SCHOLAR: [
    { field: "scholarId", type: "string", required: true, example: "BT-CO-001" },
    { field: "fullName", type: "string", required: true, example: "Ana Pérez Gómez" },
    { field: "country", type: "string", required: true, enumCategory: "country", example: "COLOMBIA" },
    { field: "cohort", type: "string", required: true, example: "2025" },
    { field: "university", type: "string", required: true, example: "Universidad Nacional de Colombia" },
    { field: "academicProgram", type: "string", required: true, example: "Computer Science" },
    { field: "gender", type: "string", required: true, example: "Female" },
    { field: "programStatus", type: "string", enumCategory: "program_status", example: "ACTIVE" },
    { field: "currentSemester", type: "int" },
    { field: "currentMentor", type: "string" },
    { field: "ethnicGroup", type: "string" },
    { field: "departmentOrigin", type: "string" },
    { field: "municipalityOrigin", type: "string" },
    { field: "currentDepartment", type: "string" },
    { field: "currentMunicipality", type: "string" },
    { field: "startDate", type: "date" },
    { field: "expectedEndDate", type: "date" },
    { field: "driveFolderUrl", type: "string" },
  ],
  ACADEMIC_TERM: [
    { field: "scholarId", type: "string", required: true, example: "BT-CO-001" },
    { field: "term", type: "string", required: true, example: "2025-1" },
    { field: "enrollmentStatus", type: "string" },
    { field: "creditsEnrolled", type: "int" },
    { field: "creditsCompleted", type: "int" },
    { field: "accumulatedCredits", type: "int" },
    { field: "totalProgramCredits", type: "int" },
    { field: "progressPercentage", type: "float" },
    { field: "gpa", type: "float", example: "4.1" },
    { field: "accumulatedGpa", type: "float" },
    { field: "failedSubjectsCount", type: "int" },
    { field: "failedSubjectsDetail", type: "string" },
    { field: "expectedProgressStatus", type: "string", enumCategory: "academic_progress_status" },
    { field: "academicStatus", type: "string" },
    { field: "isLeveling", type: "boolean" },
    { field: "receivedSupport", type: "boolean" },
  ],
  MONTHLY_CHECKIN: [
    { field: "scholarId", type: "string", required: true, example: "BT-CO-001" },
    { field: "reportingMonth", type: "string", required: true, example: "2026-06" },
    { field: "submissionId", type: "string" },
    { field: "submissionDate", type: "date" },
    { field: "scholarName", type: "string" },
    { field: "academicSelfReport", type: "string" },
    { field: "academicLevel", type: "string" },
    { field: "emotionalSelfReport", type: "string" },
    { field: "psychosocialLevel", type: "string" },
    { field: "externalFactorReport", type: "string" },
    { field: "externalFactorLevel", type: "string" },
    { field: "finalStatus", type: "string", example: "Estable" },
    { field: "country", type: "string", enumCategory: "country" },
    { field: "cohort", type: "string" },
    { field: "university", type: "string" },
    { field: "sourceForm", type: "string" },
  ],
  MENTOR_REPORT: [
    { field: "scholarId", type: "string", required: true, example: "BT-CO-001" },
    { field: "reportingMonth", type: "string", example: "2026-06" },
    { field: "submissionId", type: "string" },
    { field: "mentorName", type: "string" },
    { field: "sessionDate", type: "date" },
    { field: "sessionType", type: "string" },
    { field: "sessionSummary", type: "string" },
    { field: "permanenceRisk", type: "string", example: "Bajo" },
    { field: "academicStatus", type: "string" },
    { field: "approvedCoursesCount", type: "int" },
    { field: "atRiskCoursesCount", type: "int" },
    { field: "psychosocialStatus", type: "string" },
    { field: "accompanimentPlan", type: "string" },
    { field: "nextSteps", type: "string" },
    { field: "individualTutoring", type: "int" },
    { field: "groupTutoring", type: "int" },
    { field: "individualMentoring", type: "int" },
    { field: "groupMentoring", type: "int" },
    { field: "workshops", type: "int" },
    { field: "country", type: "string", enumCategory: "country" },
    { field: "cohort", type: "string" },
    { field: "university", type: "string" },
  ],
  SUPPORT_ACTIVITY: [
    { field: "scholarId", type: "string", required: true, example: "BT-CO-001" },
    { field: "period", type: "string", required: true, example: "2026-06" },
    { field: "activityType", type: "string", required: true, enumCategory: "activity_type", example: "INDIVIDUAL_TUTORING" },
    { field: "activityCount", type: "int", example: "2" },
    { field: "attendanceStatus", type: "string" },
    { field: "participationRate", type: "float" },
    { field: "source", type: "string", example: "import" },
    { field: "notes", type: "string" },
    { field: "country", type: "string", enumCategory: "country" },
    { field: "cohort", type: "string" },
    { field: "university", type: "string" },
  ],
  SCHOLAR_REQUEST: [
    { field: "scholarId", type: "string", required: true, example: "BT-CO-001" },
    { field: "requestType", type: "string", required: true, example: "Academic support" },
    { field: "submissionId", type: "string" },
    { field: "submissionDate", type: "date" },
    { field: "firstName", type: "string" },
    { field: "lastName", type: "string" },
    { field: "requestDescription", type: "string" },
    { field: "status", type: "string", enumCategory: "request_status", example: "SUBMITTED" },
    { field: "responseChannel", type: "string" },
    { field: "observations", type: "string" },
    { field: "owner", type: "string" },
    { field: "country", type: "string", enumCategory: "country" },
    { field: "cohort", type: "string" },
    { field: "university", type: "string" },
  ],
  FINANCIAL_INPUT: [
    { field: "scholarId", type: "string", required: true, example: "BT-CO-001" },
    { field: "period", type: "string", required: true, example: "2026" },
    { field: "costCategory", type: "string", required: true, enumCategory: "cost_category", example: "Tuition" },
    { field: "costAmount", type: "float", required: true, example: "5000000" },
    { field: "currency", type: "string", required: true, example: "COP" },
    { field: "fundingSource", type: "string" },
    { field: "isDirectCost", type: "boolean" },
    { field: "notes", type: "string" },
    { field: "country", type: "string", enumCategory: "country" },
    { field: "cohort", type: "string" },
    { field: "university", type: "string" },
  ],
};

/** Friendly header aliases accepted in addition to the canonical field names. */
export const HEADER_ALIASES: Record<string, string> = {
  id_becario: "scholarId",
  id: "scholarId",
  nombre_completo: "fullName",
  pais: "country",
  cohorte: "cohort",
  universidad: "university",
};
